# Generated by Django 4.2 on 2025-07-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('position', models.CharField(max_length=100, verbose_name='المنصب')),
                ('speaker_type', models.CharField(choices=[('board', 'عضو مجلس إدارة'), ('executive', 'مدير تنفيذي'), ('visitor', 'زائر'), ('unknown', 'غير معروف')], default='board', max_length=20, verbose_name='نوع المتحدث')),
                ('voice_embedding', models.BinaryField(blank=True, null=True, verbose_name='بصمة الصوت')),
                ('reference_audio', models.FileField(blank=True, null=True, upload_to='reference_audio/', verbose_name='ملف صوتي مرجعي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'متحدث',
                'verbose_name_plural': 'متحدثون',
            },
        ),
    ]
