# Generated by Django 4.2 on 2025-07-01 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('speaker_identification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الاجتماع')),
                ('date', models.DateField(verbose_name='تاريخ الاجتماع')),
                ('description', models.TextField(blank=True, verbose_name='وصف الاجتماع')),
                ('audio_file', models.FileField(upload_to='meeting_audio/', verbose_name='ملف التسجيل الصوتي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('processed', models.BooleanField(default=False, verbose_name='تمت المعالجة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اجتماع',
                'verbose_name_plural': 'اجتماعات',
            },
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField(verbose_name='وقت البداية (بالثواني)')),
                ('end_time', models.FloatField(verbose_name='وقت النهاية (بالثواني)')),
                ('text', models.TextField(verbose_name='النص')),
                ('confidence', models.FloatField(default=0.0, verbose_name='نسبة الثقة')),
                ('is_personal', models.BooleanField(default=False, verbose_name='محادثة شخصية')),
                ('is_decision', models.BooleanField(default=False, verbose_name='قرار')),
                ('is_action_item', models.BooleanField(default=False, verbose_name='مهمة')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='transcription.meeting')),
                ('speaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segments', to='speaker_identification.speaker')),
            ],
            options={
                'verbose_name': 'مقطع نصي',
                'verbose_name_plural': 'مقاطع نصية',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='MeetingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(verbose_name='ملخص الاجتماع')),
                ('decisions', models.TextField(verbose_name='القرارات')),
                ('action_items', models.TextField(verbose_name='المهام')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='transcription.meeting')),
            ],
            options={
                'verbose_name': 'تقرير اجتماع',
                'verbose_name_plural': 'تقارير اجتماعات',
            },
        ),
    ]
